project:
  type: website
  output-dir: docs

website:
  title: "hannahyma.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: 
      light: lux
      dark: slate
    css: styles.css
    toc: true
    page-layout: full



